// Default wordlists
export const wordlists = {
    users: {
        'top-users': ['admin', 'root', 'administrator', 'user', 'test', 'guest', 'info', 'adm', 'mysql', 'user1', 'oracle', 'ftp', 'pi', 'postgres', 'backup', 'git', 'support', 'webmaster', 'www', 'ubuntu'],
        'common-users': ['admin', 'root', 'administrator', 'user', 'test', 'guest', 'info', 'adm', 'mysql', 'user1', 'oracle', 'ftp', 'pi', 'postgres', 'backup', 'git', 'support', 'webmaster', 'www', 'ubuntu', 'demo', 'service', 'sysadmin', 'operator', 'developer', 'manager', 'supervisor', 'superuser', 'tech', 'student', 'teacher', 'sales', 'marketing', 'account', 'finance', 'hr', 'helpdesk', 'security', 'audit', 'monitor', 'backupadmin', 'dbadmin', 'webadmin', 'server', 'client', 'customer', 'visitor', 'anonymous', 'public', 'private', 'internal', 'external', 'temp', 'temporary', 'test1', 'test2', 'test3', 'testuser', 'testadmin', 'testaccount', 'dummy', 'fake', 'example', 'sample', 'standard', 'default', 'generic', 'shared', 'common', 'limited', 'unlimited', 'poweruser', 'normaluser', 'basicuser', 'advanceduser', 'expert', 'novice', 'beginner', 'intermediate', 'professional', 'amateur', 'master', 'slave', 'primary', 'secondary', 'backupuser', 'restore', 'import', 'export', 'upload', 'download', 'sync', 'async', 'batch', 'cron', 'daemon', 'system', 'kernel', 'shell', 'bash', 'zsh', 'fish', 'sh'],
        'large-users': Array(1000).fill().map((_, i) => `user${i+1}`) // Placeholder
    },
    passwords: {
        'top-passwords': ['123456', 'password', '12345678', 'qwerty', '123456789', '12345', '1234', '111111', '1234567', 'dragon', '123123', 'baseball', 'abc123', 'football', 'monkey', 'letmein', 'shadow', 'master', '666666', 'qwertyuiop'],
        'common-passwords': ['123456', 'password', '12345678', 'qwerty', '123456789', '12345', '1234', '111111', '1234567', 'dragon', '123123', 'baseball', 'abc123', 'football', 'monkey', 'letmein', 'shadow', 'master', '666666', 'qwertyuiop', '123321', 'mustang', '1234567890', 'michael', '654321', 'superman', '1qaz2wsx', '7777777', '121212', '000000', 'qazwsx', '123qwe', 'killer', 'trustno1', 'jordan', 'jennifer', 'zxcvbnm', 'asdfgh', 'hunter', 'buster', 'soccer', 'harley', 'batman', 'andrew', 'tigger', 'sunshine', 'iloveyou', 'fuckme', '2000', 'charlie', 'robert', 'thomas', 'hockey', 'ranger', 'daniel', 'starwars', 'klaster', '112233', 'george', 'computer', 'michelle', 'jessica', 'pepper', '1111', 'zxcvbn', '555555', '11111111', '131313', 'freedom', '777777', 'pass', 'maggie', '159753', 'aaaaaa', 'ginger', 'princess', 'joshua', 'cheese', 'amanda', 'summer', 'love', 'ashley', 'nicole', 'chelsea', 'biteme', 'matthew', 'access', 'yankees', '987654321', 'dallas', 'austin', 'thunder', 'taylor', 'matrix', 'minecraft', 'whatever', 'hello', 'hello123', 'fuckyou', 'secret', 'fuck', 'asdf', '123abc', '123asd', 'qwe123', 'qweasd', 'qweqwe', 'asdasd', 'asd123', 'zxc123', 'zxczxc', '1q2w3e', '1q2w3e4r', '1q2w3e4r5t', 'q1w2e3', 'q1w2e3r4', 'q1w2e3r4t5', '1qazxsw2', '!@#$%^', '!@#$%^&*', '!@#$%^&*()', 'qwerty123', 'password1', 'password123', 'admin123', 'welcome123', 'login123', 'pass123', 'passw0rd', 'p@ssword', 'p@ssw0rd', 'pass@123', 'admin@123', 'welcome@123', 'login@123'],
        'rockyou-light': Array(1000).fill().map((_, i) => `pass${i+1}`) // Placeholder
    }
};

export const MAX_FILE_LINES = 1000;